
version: '3.8'

services:
  app:
    image: $DOCKERHUB_USERNAME/app-image:latest
    container_name: app-container
    restart: unless-stopped
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    networks:
      - app-network

  webserver:
    image: $DOCKERHUB_USERNAME/nginx-image:latest
    container_name: nginx-container
    restart: unless-stopped
    ports:
      - "8090:80"
    networks:
      - app-network

networks:
  app-network:
