version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: gesto-rest-app
    container_name: gesto-rest-app
    volumes:
      - .:/var/www
    ports:
      - "8090:9000"
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - APP_KEY=${APP_KEY}
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=restaurante7
      - DB_USERNAME=root
      - DB_PASSWORD=1q2w3e4r
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    container_name: gesto-rest-db
    environment:
      MYSQL_DATABASE: restaurante7
      MYSQL_USER: root
      MYSQL_PASSWORD: ""
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306" 
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3


volumes:
  db_data:
