services:
  gesto-rest-app:
    image: mruizgl/gesto-rest-app-image
    container_name: gesto-rest-app-container
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: gesto-rest
      SERVICE_TAGS: dev
    working_dir: /var/www
    networks:
      - gesto-rest-network

  gesto-rest-webserver:
    image: mruizgl/gesto-rest-nginx-webserver-image
    container_name: gesto-rest-webserver-container
    restart: unless-stopped
    ports:
      - "8090:80"
    networks:
      - gesto-rest-network

  gesto-rest-mysqldb:
    image: mysql:8.3.0
    container_name: gesto-rest-mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: 1q2w3e4r
    volumes:
      - gesto-rest-dbdata:/var/lib/mysql
      - ./docker-compose/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - gesto-rest-network

volumes:
  gesto-rest-dbdata:
networks:
  gesto-rest-network: