version: '3'
services:
  app-personas:
    image: jciespuerto/app-restaurantes-image
    container_name: app-restaurantes-container
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
#    volumes:
#      - .:/var/www
    networks:
      - app-restaurantes-network

  app-personas-webserver:
    image: jciespuerto/app-restaurantes-nginx-webserver-image
    container_name: app-restaurantes-nginx-webserver
    restart: unless-stopped
    ports:
      - "8080:80"
#    volumes:
#     - .:/var/www
#      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - app-restaurantes-network

  app-personas-mysqldb:
    image: mysql:8.3.0
    container_name: app-restaurantes-mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: 1q2w3e4r
#    ports:
#      - "3306:3306"
    volumes:
      - app-restaurantes-dbdata
      - ./docker-compose/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-restaurantes-network

volumes:
  app-restaurantes-dbdata:
networks:
  app-restaurantes-network: