version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: gesto-rest-app
    container_name: gesto-rest-app
    volumes:
      - .:/var/www
    ports:
      - "8090:9000"
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - APP_KEY=${APP_KEY}
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: gesto-rest-db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE=${DB_DATABASE}
      MYSQL_USER=${DB_USERNAME}
      MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db_data:
