jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      APP_KEY: ${{ secrets.APP_KEY }}
      DB_DATABASE: ${{ secrets.DB_DATABASE }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ""

    steps:
    - name: Wait for MySQL
      working-directory: gesto-rest
      run: |
        until docker exec gesto-rest-db mysqladmin ping -h localhost --silent; do
          echo "Waiting for MySQL to be ready..."
          sleep 5
        done
        
      # Clonar el repositorio
      - name: Checkout Code
        uses: actions/checkout@v3

      # Instalar Docker Compose
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      # Navegar al directorio de gesto-rest
      - name: Navigate to gesto-rest
        working-directory: gesto-rest
        run: ls -la

      # Construir y ejecutar Docker Compose
      - name: Build and Deploy
        working-directory: gesto-rest
        run: |
          docker-compose down || true
          docker-compose up -d --build

      # Ejecutar comandos de Laravel
      - name: Run Laravel Commands
        working-directory: gesto-rest
        run: |
          docker exec gesto-rest-app php artisan migrate --force
          docker exec gesto-rest-app php artisan db:seed --class=UsersTableSeeder --force
          docker exec gesto-rest-app php artisan storage:link