name: Deploy Laravel App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Instalar Docker Compose
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      # Clonar el repositorio
      - name: Checkout Code
        uses: actions/checkout@v3

      # Navegar al subdirectorio del proyecto
      - name: Navigate to gesto-rest
        working-directory: gesto-rest
        run: ls

      # Configurar Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Construir y ejecutar Docker Compose
      - name: Build and Deploy
        working-directory: gesto-rest
        run: |
          docker-compose down
          docker-compose up -d --build

      # Ejecutar comandos de Laravel
      - name: Run Laravel Commands
        working-directory: gesto-rest
        run: |
          docker exec gesto-rest-app php artisan migrate --force
          docker exec gesto-rest-app php artisan db:seed --class=UsersTableSeeder
